name: school_bell
publish_to: 'none'

version: 2.1.0+4

environment:
  sdk: 3.7.2
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager_plus: 4.0.8
  audioplayers: 6.5.0
  file_picker: 10.3.2
  flutter_foreground_task: 9.1.0
  flutter_svg: 2.2.0
  fluttertoast: 8.2.12
  in_app_update: 4.2.3
  numberpicker: 2.1.2
  package_info_plus: 8.3.1
  permission_handler: 12.0.1
  provider: 6.1.5+1
  shared_preferences: 2.5.3
  store_redirect: 2.0.4
  url_launcher: 6.3.2
  vector_graphics: 1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  flutter_oss_licenses: 3.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/character/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
