name: school_bell
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: LevelTwo
      fonts:
        - asset: assets/fonts/Nexon-Lv2-Gothic.otf
        - asset: assets/fonts/Nexon-Lv2-Gothic-Light.otf
          weight: 300
        - asset: assets/fonts/Nexon-Lv2-Gothic-Medium.otf
          weight: 500
        - asset: assets/fonts/Nexon-Lv2-Gothic-Bold.otf
          weight: 700
