name: school_bell
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: 3.2.6
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager_plus: 3.0.4
  audioplayers: 5.2.1
  editable_number_picker:
    path: ../editable_number_picker/
  file_picker: 6.1.1
  flutter_local_notifications: 16.3.2
  flutter_svg: 2.0.9
  fluttertoast: 8.2.4
  in_app_update: 4.2.2
  package_info_plus: 5.0.1
  provider: 6.1.1
  shared_preferences: 2.2.2
  url_launcher: 6.2.4
  vector_graphics: 1.1.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  flutter_oss_licenses: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/character/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
