name: school_bell
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: 3.2.6
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager_plus: 3.0.4
  audioplayers: 5.2.1
  editable_number_picker:
    path: ../editable_number_picker/
  file_picker: 6.1.1
  flutter_local_notifications: 16.3.2
  fluttertoast: 8.2.4
  in_app_update: 4.2.2
  move_to_background: 1.0.2
  package_info_plus: 5.0.1
  provider: 6.1.1
  shared_preferences: 2.2.2
  store_redirect: 2.0.1
  url_launcher: 6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  flutter_oss_licenses: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/character/
  fonts:
    - family: LevelTwo
      fonts:
        - asset: assets/fonts/Nexon-Lv2-Gothic.otf
        - asset: assets/fonts/Nexon-Lv2-Gothic-Light.otf
          weight: 300
        - asset: assets/fonts/Nexon-Lv2-Gothic-Medium.otf
          weight: 500
        - asset: assets/fonts/Nexon-Lv2-Gothic-Bold.otf
          weight: 700
